@echo off
::----------------------------------------------------------
::  InitGitRepo_Safe.bat  —— 禁止在桌面运行的安全初始化
::----------------------------------------------------------
chcp 65001 >nul
title 初始化 Git 仓库  (Safe Mode)

:: 0. 取当前完整路径（兼容中文）
for %%A in ("%CD%") do set "CURRP=%%~fA"

:: 只要路径里出现 Desktop 或桌面就禁止
echo %CURRP% | find /i "Desktop" >nul && goto :BlockDesktop
echo %CURRP% | find /i "桌面"   >nul && goto :BlockDesktop
goto :Continue

:BlockDesktop
echo [错误] 不能在桌面和桌面文件夹初始化 Git 仓库，请换到D盘项目文件夹！
echo(ERROR: Desktop is not allowed, switch to your project folder!
pause & exit /b

:Continue
:: 1. 如果已有 .git 直接退出
if exist .git (
    echo 当前目录已是 Git 仓库，无需重复初始化。
    echo(Already a Git repo, nothing to do.
    timeout /t 3 >nul
    exit /b
)

:: 2. 初始化
echo [1/5] 初始化仓库 ... (git init)
git init >nul
if errorlevel 1 (
    echo 初始化失败，请确认 Git 已安装并加入 PATH。
    echo(Init failed, please check Git installation.
    pause & exit /b
)

:: 3. 写入默认 .gitignore（若已存在则跳过）
if not exist .gitignore (
    echo [2/5] 创建 .gitignore 过滤子仓库/node_modules等
    (
        echo # === auto-generated by InitGitRepo_Safe.bat ===
        echo node_modules/
        echo *.log
        echo .cache/
        echo dist/
        echo build/
        echo .vscode/
        echo # 忽略所有嵌套的 Git 仓库
        echo **/.git/
    ) > .gitignore
)

:: 4. 添加文件（受 .gitignore 保护）
echo [3/5] 添加文件 ... (git add -A)
git add -A

:: 5. 配置局部用户
echo [4/5] 配置用户名/邮箱 ... (git config user.name/email)
git config user.name  "TangShiMei02"
git config user.email "2244182951@qq.com"

:: 6. 提交
echo [5/5] 提交初始版本 ... (git commit -m "initial commit")
git commit -m "initial commit" >nul
if errorlevel 1 (
    echo 提交失败，可能没有可提交的文件或配置错误。
    echo(Commit failed, maybe nothing to commit or config error.
    pause & exit /b
)

:: 7. 验证
git log --oneline -1 | findstr /i "initial commit" >nul
if errorlevel 1 (
    echo 提交验证失败，请手动检查。
    echo(Commit verification failed, please check manually.
    pause & exit /b
)

echo ===== 初始化成功！3 秒后自动退出 =====
echo(===== Init SUCCESS! Auto exit in 3s =====
timeout /t 3 >nul